version: "3"

services:
  app:
    container_name: notification-service
    image: golang:1.17.2-stretch
    command: ["sh", "-c", "go mod download && go run server/main.go"]
    ports:
      - '2121:2121'
    environment:
      - PORT=2121
    working_dir: /app
    volumes:
      - ./:/app