// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmailNotificationClient is the client API for EmailNotification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailNotificationClient interface {
	SendEmail(ctx context.Context, in *EmailMessage, opts ...grpc.CallOption) (*EmailMessageResponse, error)
}

type emailNotificationClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailNotificationClient(cc grpc.ClientConnInterface) EmailNotificationClient {
	return &emailNotificationClient{cc}
}

func (c *emailNotificationClient) SendEmail(ctx context.Context, in *EmailMessage, opts ...grpc.CallOption) (*EmailMessageResponse, error) {
	out := new(EmailMessageResponse)
	err := c.cc.Invoke(ctx, "/EmailNotification/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailNotificationServer is the server API for EmailNotification service.
// All implementations must embed UnimplementedEmailNotificationServer
// for forward compatibility
type EmailNotificationServer interface {
	SendEmail(context.Context, *EmailMessage) (*EmailMessageResponse, error)
	mustEmbedUnimplementedEmailNotificationServer()
}

// UnimplementedEmailNotificationServer must be embedded to have forward compatible implementations.
type UnimplementedEmailNotificationServer struct {
}

func (UnimplementedEmailNotificationServer) SendEmail(context.Context, *EmailMessage) (*EmailMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedEmailNotificationServer) mustEmbedUnimplementedEmailNotificationServer() {}

// UnsafeEmailNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailNotificationServer will
// result in compilation errors.
type UnsafeEmailNotificationServer interface {
	mustEmbedUnimplementedEmailNotificationServer()
}

func RegisterEmailNotificationServer(s grpc.ServiceRegistrar, srv EmailNotificationServer) {
	s.RegisterService(&EmailNotification_ServiceDesc, srv)
}

func _EmailNotification_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailNotificationServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmailNotification/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailNotificationServer).SendEmail(ctx, req.(*EmailMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailNotification_ServiceDesc is the grpc.ServiceDesc for EmailNotification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailNotification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EmailNotification",
	HandlerType: (*EmailNotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _EmailNotification_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/email.proto",
}
